---
dist: bionic
language: python
services:
- docker
script:
- tox
deploy:
- provider: script
  script: TWINE_PASSWORD=$TESTPYPI_TOKEN tox -e release
  on:
    branch: develop
- provider: script
  script: TWINE_PASSWORD=$PYPI_TOKEN TWINE_REPOSITORY=pypi tox -e release
  on:
    branch: main
