---
dist: bionic
language: python
python:
- "3.6"
- "3.7"
- "3.8"
install:
- pip install tox
script:
- tox
deploy:
- provider: script
  script: TWINE_PASSWORD=$TESTPYPI_TOKEN tox -e release
  on:
    branch: develop
- provider: script
  script: TWINE_PASSWORD=$PYPI_TOKEN TWINE_REPOSITORY=pypi tox -e release
  on:
    branch: main
